version: "3.9"

services:
  database:
    image: postgres:15-alpine
    container_name: poke_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pokemons
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - poke_net

  backend:
    build: ./backend
    container_name: poke_backend
    ports:
      - "4000:4000"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: pokemons
      JWT_SECRET: tu_secreto_super_seguro_cambiar_en_produccion
    depends_on:
      - database
    networks:
      - poke_net

  frontend:
    build: ./frontend
    container_name: poke_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - poke_net

volumes:
  postgres_data:

networks:
  poke_net:
    driver: bridge

